/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staff.management.system;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aadarsha
 */
public class AddEmployees extends javax.swing.JPanel {
    JPanel jp;
    DBConnection db;
    /**
     * Creates new form AddEmployees
     */
    public AddEmployees(JPanel jp) {
        initComponents();
        db=new DBConnection();
        this.jp=jp;
    }
    public AddEmployees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        mstatus = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        MiddleName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        cnumber = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        AddressPanel = new javax.swing.JPanel();
        stateLabel = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        street = new javax.swing.JTextField();
        streetLabel = new javax.swing.JLabel();
        ward = new javax.swing.JTextField();
        wardLabel = new javax.swing.JLabel();
        teleLabel = new javax.swing.JLabel();
        telephone = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        mobileLabel = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        single = new javax.swing.JRadioButton();
        married = new javax.swing.JRadioButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        spercent = new javax.swing.JTextField();
        schoolLabel = new javax.swing.JLabel();
        sinsti = new javax.swing.JTextField();
        plus2Label = new javax.swing.JLabel();
        ppercent = new javax.swing.JTextField();
        pinsti = new javax.swing.JTextField();
        bpercent = new javax.swing.JTextField();
        bachelorLabel = new javax.swing.JLabel();
        binsti = new javax.swing.JTextField();
        masterLabel = new javax.swing.JLabel();
        mpercent = new javax.swing.JTextField();
        minsti = new javax.swing.JTextField();
        langLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        language = new javax.swing.JTextArea();
        trainingLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        training = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        experience = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        schoolLabel1 = new javax.swing.JLabel();
        designation = new javax.swing.JComboBox<>();
        schoolLabel2 = new javax.swing.JLabel();
        insurance = new javax.swing.JTextField();
        schoolLabel3 = new javax.swing.JLabel();
        AddEmployee = new javax.swing.JPanel();
        addLabel = new javax.swing.JLabel();
        pf = new javax.swing.JCheckBox();
        schoolLabel4 = new javax.swing.JLabel();
        bsalary = new javax.swing.JTextField();
        schoolLabel5 = new javax.swing.JLabel();
        food = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(236, 236, 255));

        jScrollPane1.setBackground(new java.awt.Color(236, 236, 255));

        jPanel1.setBackground(new java.awt.Color(236, 236, 255));

        jPanel2.setBackground(new java.awt.Color(236, 236, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Myanmar Text", 1, 17))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        jLabel1.setText("Full Name");

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        jLabel3.setText("Date of Birth");

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        jLabel5.setText("Citizenship Number");

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        jLabel6.setText("Marital Status");

        FirstName.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        FirstName.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        MiddleName.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        MiddleName.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        LastName.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        LastName.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        year.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        year.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        month.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        month.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        date.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        date.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        cnumber.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        cnumber.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        genderLabel.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        genderLabel.setText("Gender");

        AddressPanel.setBackground(new java.awt.Color(236, 236, 255));
        AddressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Myanmar Text", 1, 14))); // NOI18N

        stateLabel.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        stateLabel.setText("State");

        state.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        state.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        city.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        city.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        cityLabel.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        cityLabel.setText("City");

        street.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        street.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        streetLabel.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        streetLabel.setText("Street");

        ward.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        ward.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        wardLabel.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        wardLabel.setText("Ward No.");

        javax.swing.GroupLayout AddressPanelLayout = new javax.swing.GroupLayout(AddressPanel);
        AddressPanel.setLayout(AddressPanelLayout);
        AddressPanelLayout.setHorizontalGroup(
            AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(streetLabel)
                    .addComponent(stateLabel))
                .addGap(156, 156, 156)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityLabel)
                    .addComponent(wardLabel))
                .addGap(57, 57, 57)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ward, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(195, 195, 195))
        );
        AddressPanelLayout.setVerticalGroup(
            AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressPanelLayout.createSequentialGroup()
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateLabel)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityLabel)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetLabel)
                    .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wardLabel)
                    .addComponent(ward, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        teleLabel.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        teleLabel.setText("Telephone Number");

        telephone.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        telephone.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        emailLabel.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        emailLabel.setText("Email");

        email.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        mobileLabel.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        mobileLabel.setText("Mobile Number");

        mobile.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        mobile.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        male.setBackground(new java.awt.Color(236, 236, 255));
        gender.add(male);
        male.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        male.setText("Male");

        female.setBackground(new java.awt.Color(236, 236, 255));
        gender.add(female);
        female.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        female.setText("Female");

        single.setBackground(new java.awt.Color(236, 236, 255));
        mstatus.add(single);
        single.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        single.setText("Single");

        married.setBackground(new java.awt.Color(236, 236, 255));
        mstatus.add(married);
        married.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        married.setText("Married");

        jLabel34.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel34.setText("First Name");

        jLabel35.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel35.setText("Middle Name");

        jLabel36.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel36.setText("Last Name");

        jLabel37.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel37.setText("Year");

        jLabel38.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel38.setText("Month");

        jLabel39.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel39.setText("Day");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(teleLabel)
                                .addGap(82, 82, 82)
                                .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AddressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(78, 78, 78)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(154, 154, 154)
                                        .addComponent(female))
                                    .addComponent(male)
                                    .addComponent(cnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderLabel)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(emailLabel)
                                    .addGap(178, 178, 178)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(209, 209, 209))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(mobileLabel)
                                                .addComponent(jLabel6))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(154, 154, 154)
                                                    .addComponent(single))
                                                .addComponent(married)
                                                .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                    .addGap(129, 129, 129)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31)
                                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel34)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel37)
                                                    .addGap(131, 131, 131)
                                                    .addComponent(jLabel38)))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(MiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel35))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel36)
                                                        .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(47, 47, 47)
                                                    .addComponent(jLabel39))))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(MiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel37))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel38)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(male, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(female, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(married, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(single, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(genderLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cnumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teleLabel)
                    .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileLabel)
                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(236, 236, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Qualifications", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Myanmar Text", 1, 14))); // NOI18N

        spercent.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N

        schoolLabel.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        schoolLabel.setText("School");

        sinsti.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N

        plus2Label.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        plus2Label.setText("Plus Two (+2)");

        ppercent.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N

        pinsti.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N

        bpercent.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N

        bachelorLabel.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        bachelorLabel.setText("Bachelors");

        binsti.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N

        masterLabel.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        masterLabel.setText("Masters");

        mpercent.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N

        minsti.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N

        langLabel.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        langLabel.setText("Language");

        language.setColumns(20);
        language.setRows(5);
        jScrollPane2.setViewportView(language);

        trainingLabel.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        trainingLabel.setText("Training");

        training.setColumns(20);
        training.setRows(5);
        jScrollPane3.setViewportView(training);

        jLabel21.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        jLabel21.setText("Experience");

        experience.setColumns(20);
        experience.setRows(5);
        jScrollPane4.setViewportView(experience);

        jLabel22.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        jLabel22.setText("%");

        jLabel23.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        jLabel23.setText("%");

        jLabel24.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        jLabel24.setText("%");

        jLabel25.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        jLabel25.setText("%");

        jLabel26.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel26.setText("Institution");

        jLabel27.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel27.setText("Institution");

        jLabel28.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel28.setText("Institution");

        jLabel29.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel29.setText("Institution");

        jLabel30.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel30.setText("Percentage");

        jLabel31.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel31.setText("Percentage");

        jLabel32.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel32.setText("Percentage");

        jLabel33.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel33.setText("Percentage");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(langLabel)
                            .addGap(125, 125, 125)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(bachelorLabel)
                            .addGap(126, 126, 126)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(bpercent, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel23))
                                .addComponent(jLabel31))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel28)
                                .addComponent(binsti, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(schoolLabel)
                        .addGap(146, 146, 146)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(spercent, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel22))
                            .addComponent(jLabel30))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(sinsti, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(trainingLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(masterLabel)
                            .addGap(138, 138, 138)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(mpercent, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel25))
                                .addComponent(jLabel33))
                            .addGap(17, 17, 17)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel29)
                                .addComponent(minsti, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(plus2Label)
                        .addGap(97, 97, 97)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ppercent, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24))
                            .addComponent(jLabel32))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(pinsti, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolLabel)
                    .addComponent(spercent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sinsti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(plus2Label)
                    .addComponent(ppercent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinsti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel31)
                    .addComponent(jLabel33))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bachelorLabel)
                    .addComponent(bpercent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(binsti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masterLabel)
                    .addComponent(mpercent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minsti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(langLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trainingLabel)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBackground(new java.awt.Color(236, 236, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Job Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Myanmar Text", 1, 14))); // NOI18N

        schoolLabel1.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        schoolLabel1.setText("Provident Fund");

        designation.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        designation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principal", "Coordinator", "Accountant", "Receptionist", "Teacher", "Sister", "Driver", "Ex-Employee" }));

        schoolLabel2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        schoolLabel2.setText("Designation");

        insurance.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N

        schoolLabel3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        schoolLabel3.setText("Insurance");

        AddEmployee.setBackground(new java.awt.Color(26, 35, 126));
        AddEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddEmployeeMouseClicked(evt);
            }
        });

        addLabel.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        addLabel.setForeground(new java.awt.Color(255, 255, 255));
        addLabel.setText("Add Employee");

        javax.swing.GroupLayout AddEmployeeLayout = new javax.swing.GroupLayout(AddEmployee);
        AddEmployee.setLayout(AddEmployeeLayout);
        AddEmployeeLayout.setHorizontalGroup(
            AddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEmployeeLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(addLabel)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        AddEmployeeLayout.setVerticalGroup(
            AddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pf.setBackground(new java.awt.Color(236, 236, 255));
        pf.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        pf.setText("10%");
        pf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfActionPerformed(evt);
            }
        });

        schoolLabel4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        schoolLabel4.setText("Basic Salary");

        bsalary.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N

        schoolLabel5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        schoolLabel5.setText("Food Allowance");

        food.setBackground(new java.awt.Color(236, 236, 255));
        food.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        food.setText("*Select only for teachers");
        food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schoolLabel2)
                    .addComponent(schoolLabel4)
                    .addComponent(schoolLabel3))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(designation, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insurance, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(267, 267, 267)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(schoolLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(pf))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(schoolLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(food)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schoolLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(schoolLabel1)
                        .addComponent(pf))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(schoolLabel4)
                        .addComponent(bsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(schoolLabel5)
                            .addComponent(food))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(schoolLabel3)
                            .addComponent(insurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEmployeeMouseClicked
        // TODO add your handling code here:
        male.setActionCommand("Male");
        female.setActionCommand("Female");
        married.setActionCommand("Married");
        single.setActionCommand("Single");
        addEmployees();
    }//GEN-LAST:event_AddEmployeeMouseClicked

    private void pfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfActionPerformed

    private void foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodActionPerformed
    private void addEmployees(){
        stmt=db.statementObject();
        jp.removeAll();
        jp.add(new AddEmployees(jp));
        jp.revalidate();
        
        String fname=FirstName.getText(), mname=MiddleName.getText(), lname=LastName.getText();
        String acity=city.getText(), astate=state.getText(),award=ward.getText(), astreet=street.getText();
        String dob=year.getText()+month.getText()+date.getText();
        String agender=gender.getSelection().getActionCommand();
        String amstatus=mstatus.getSelection().getActionCommand();
        String aemail=email.getText();
        String school=spercent.getText()+", "+sinsti.getText();        
        String plustwo=ppercent.getText()+", "+pinsti.getText();        
        String bachelors=bpercent.getText()+", "+binsti.getText();        
        String masters=mpercent.getText()+", "+minsti.getText();        
        String alanguage=language.getText();                
        String atraining=training.getText();        
        String aexperience=experience.getText();
        int position=designation.getSelectedIndex()+1;
        String ainsurance=insurance.getText();
        System.out.println(bsalary.getText());
        double absalary=Double.valueOf(bsalary.getText());
        boolean providentcheck=pf.isSelected();
        boolean foodcheck=food.isSelected();
        String sql="INSERT INTO employee(fname,mname,lname,city,state,ward,street,dob,gender,email,m_status) VALUES"
                + "('"+fname+"','"+mname+"','"+lname+"','"+acity+"','"+astate+"','"+award+"','"+astreet+"','"+dob+"','"+agender+"','"+aemail+"','"+amstatus+"')";
        int eid=-1;
        String providentfund="0";
        String food="0";
        String salarybt="";
        String t_salary = "";
        String tax="1";
        try{
            stmt.execute(sql);
            System.out.println("Data Inserted in Employee");
            sql="SELECT e_id FROM employee ORDER BY e_id DESC LIMIT 1";
            ResultSet rs=stmt.executeQuery(sql);
            while(rs.next()){
                eid=rs.getInt("e_id");
            }
            try{
                sql="INSERT INTO skills(school,plustwo,bachelors,masters,language,training,experience,e_id) VALUES"
                    + "('"+school+"','"+plustwo+"','"+bachelors+"','"+masters+"','"+alanguage+"','"+atraining+"','"+aexperience+"',"+eid+")";

                stmt.execute(sql);
                System.out.println("Data Inserted in Skills");
                try{
                    sql="SELECT Tax,Food FROM job WHERE j_position="+position;
                    rs=stmt.executeQuery(sql);
                    while(rs.next()){
                        tax=rs.getString("Tax");
                        food=rs.getString("Food");
                    }
                    if(providentcheck && foodcheck){
                        providentfund=String.valueOf(0.1*absalary);
                    }
                    else if(providentcheck && !foodcheck){
                        providentfund=String.valueOf(0.1*absalary);
                        food="0";
                    }
                    else if(!providentcheck && !foodcheck){
                        food="0";
                    }
                    salarybt=String.valueOf((absalary-Double.parseDouble(providentfund)-Double.parseDouble(ainsurance)+Double.parseDouble(food)));
                    t_salary=String.valueOf(Double.parseDouble(salarybt)*(1-(Double.parseDouble(tax)/100)));
                    System.out.println("Total Salary Calculated!");
                    try{

                        sql="INSERT INTO salary(e_id,j_position,bsalary,providentfund,insurance,salarybt,t_salary) VALUES"
                            + "("+eid+","+position+",'"+absalary+"','"+providentfund+"','"+ainsurance+"','"+salarybt+"','"+t_salary+"')";

                        stmt.execute(sql);
                        System.out.println("Data Inserted in Skills");
                        JOptionPane.showMessageDialog(null,"Employee added succesfully!","Success",JOptionPane.PLAIN_MESSAGE);
                    }
                    catch(  HeadlessException | SQLException e){
                        System.out.println("Data not inserted in salary " + e);
                    }
                }catch( NumberFormatException | SQLException e){
                    System.out.println("Bsalary not found" + e);
                } 
            }
            catch(SQLException e){
                System.out.println("Data not inserted in skills " + e);
            }
        }
        catch(SQLException e){
            System.out.println("Failed to insert into employee or failed to load eid " + e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddEmployee;
    private javax.swing.JPanel AddressPanel;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField MiddleName;
    private javax.swing.JLabel addLabel;
    private javax.swing.JLabel bachelorLabel;
    private javax.swing.JTextField binsti;
    private javax.swing.JTextField bpercent;
    private javax.swing.JTextField bsalary;
    private javax.swing.JTextField city;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cnumber;
    private javax.swing.JTextField date;
    private javax.swing.JComboBox<String> designation;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextArea experience;
    private javax.swing.JRadioButton female;
    private javax.swing.JCheckBox food;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField insurance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel langLabel;
    private javax.swing.JTextArea language;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton married;
    private javax.swing.JLabel masterLabel;
    private javax.swing.JTextField minsti;
    private javax.swing.JTextField mobile;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField month;
    private javax.swing.JTextField mpercent;
    private javax.swing.ButtonGroup mstatus;
    private javax.swing.JCheckBox pf;
    private javax.swing.JTextField pinsti;
    private javax.swing.JLabel plus2Label;
    private javax.swing.JTextField ppercent;
    private javax.swing.JLabel schoolLabel;
    private javax.swing.JLabel schoolLabel1;
    private javax.swing.JLabel schoolLabel2;
    private javax.swing.JLabel schoolLabel3;
    private javax.swing.JLabel schoolLabel4;
    private javax.swing.JLabel schoolLabel5;
    private javax.swing.JRadioButton single;
    private javax.swing.JTextField sinsti;
    private javax.swing.JTextField spercent;
    private javax.swing.JTextField state;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField street;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JLabel teleLabel;
    private javax.swing.JTextField telephone;
    private javax.swing.JTextArea training;
    private javax.swing.JLabel trainingLabel;
    private javax.swing.JTextField ward;
    private javax.swing.JLabel wardLabel;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
    Statement stmt;
}
